src/Models/AssetTemplate.php
<?php

namespace Bigmom\VeEditor\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Storage;

class AssetTemplate extends Model
{
    use HasFactory;

    protected $fillable = ['id', 'name', 'file_type', 'requirement', 'sequence', 'folder_id', 'created_at', 'updated_at'];

    private const ASSET_TYPE = [
        'Image',
        'Video',
        'PDF',       
    ];

    public function folder()
    {
        return $this->belongsTo(Folder::class);
    }

    public function assets()
    {
        return $this->hasMany(Asset::class);
    }

    public function getTypeNameAttribute()
    {
        return SELF::ASSET_TYPE[$this->file_type];
    }

    public function getUrlAttribute()
    {
        return count($this->assets) ? $this->assets()->latest()->first()->url : null;
    }
}

src/Http/Controllers/AssetTemplateController.php
<?php

namespace Bigmom\VeEditor\Http\Controllers;

use Bigmom\VeEditor\Http\Controllers\Controller;
use Bigmom\VeEditor\Facades\Asset as AssetManager;
use Bigmom\VeEditor\Models\Asset;
use Bigmom\VeEditor\Models\AssetTemplate;
use Bigmom\VeEditor\Models\Folder;
use Illuminate\Http\Request;

class AssetTemplateController extends Controller
{
    public function postCreate(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:191',
            'type' => 'required|integer',
            'requirement' => 'required|string|max:191',
            'file' => 'nullable|file',
            'dummy' => 'nullable',
            'folder-id' => 'required|integer|exists:folders,id'
        ]);

        if (Folder::find($request->input('folder-id'))->assetTemplates()->where('name', $request->input('name'))->exists()) {
            return redirect()
                ->back()
                ->withErrors('error', 'Name already used inside this folder.');
        }

        $template = new AssetTemplate;
        $template->name = $request->input('name');
        $template->file_type = $request->input('type');
        $template->requirement = $request->input('requirement');
        $template->folder_id = $request->input('folder-id');
        $template->sequence = AssetTemplate::where('folder_id', $template->folder_id)->count();
        $template->save();

        if ($request->has('file')) {
            $asset = new Asset;
            $asset->asset_template_id = $template->id;
            $path = $asset->store($request->file('file'));

            if ($path === false) {
                return redirect()
                    ->back()
                    ->withErrors('error', 'File limit exceeded.');
            }
    
            if ($request->has('dummy') && $request->input('dummy')) {
                $asset->dummy = 1;
            } else {
                $asset->dummy = 0;
            }
    
            $asset->save();
        }

        return redirect()
            ->back()
            ->with('success', 'success')
            ->with('message', 'Asset template created.');
    }

    public function postUpdate(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:191',
            'type' => 'required|integer',
            'requirement' => 'required|string|max:191',
            'template-id' => 'required|integer|exists:asset_templates,id', 
        ]);

        $template = AssetTemplate::find($request->input('template-id'));
        if ($template->id !== $request->input('name')) {
            if ($template->folder->assetTemplates()->where('name', $request->input('name'))->exists()) {
                return redirect()
                    ->back()
                    ->withErrors('error', 'Name already used inside this folder.');
            }
        }
        $template->name = $request->input('name');
        $template->file_type = $request->input('type');
        $template->requirement = $request->input('requirement');
        $template->save();

        return redirect()
            ->back()
            ->with('success', 'success')
            ->with('message', 'Asset template updated.');
    }

    public function postDelete(Request $request)
    {
        $request->validate([
            'template-id' => 'required|integer|exists:asset_templates,id',
        ]);

        $template = AssetTemplate::find($request->input('template-id'));
        if (count($template->assets)) {
            return redirect()
                ->back()
                ->with('error', 'error')
                ->with('message', 'Asset template not empty.');
        }
        $template->delete();

        return redirect()
            ->back()
            ->with('success', 'success')
            ->with('message', 'Asset template deleted.');
    }
    
    public function getShow(AssetTemplate $template)
    {
        $assets = $template->assets()->orderBy('updated_at', 'desc')->paginate(15);
        return view('veeditor::asset-template.show', compact('template', 'assets'));
    }

    public function postSort(Request $request)
    {
        $request->validate([
            'sequence' => 'required|string|max:191',
        ]);

        $sequence = explode(',', $request->input('sequence'));
        if (count($sequence) <= 1) return response()->json(['error' => 'Not enough elements.'], 500);
        
        $success = AssetManager::sort($sequence);

        return $success ? response()->json(['success' => 'success'])
            : response()->json(['error' => 'error'], 500);
    }
}

src/Http/Controllers/Vapor/AssetTemplateController.php
<?php

namespace Bigmom\VeEditor\Http\Controllers\Vapor;

use Bigmom\VeEditor\Http\Controllers\Controller;
use Bigmom\VeEditor\Facades\Asset as AssetManager;
use Bigmom\VeEditor\Models\Asset;
use Bigmom\VeEditor\Models\AssetTemplate;
use Bigmom\VeEditor\Models\Folder;
use Illuminate\Http\Request;

class AssetTemplateController extends Controller
{
    public function postCreate(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:191',
            'type' => 'required|integer',
            'requirement' => 'required|string|max:191',
            'folder-id' => 'required|integer|exists:folders,id'
        ]);

        if (Folder::find($request->input('folder-id'))->assetTemplates()->where('name', $request->input('name'))->exists()) {
            return redirect()
                ->back()
                ->withErrors('error', 'Name already used inside this folder.');
        }

        $template = new AssetTemplate;
        $template->name = $request->input('name');
        $template->file_type = $request->input('type');
        $template->requirement = $request->input('requirement');
        $template->folder_id = $request->input('folder-id');
        $template->sequence = AssetTemplate::where('folder_id', $template->folder_id)->count();
        $template->save();

        return $template->id
            ? response()->json(['status' => 'success', 'message' => 'Asset template successfully created.', 'template-id' => $template->id])
            : response()->json(['status' => 'error', 'message' => 'An error occured.'], 500);
    }

    public function postUpdate(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:191',
            'type' => 'required|integer',
            'requirement' => 'required|string|max:191',
            'template-id' => 'required|integer|exists:asset_templates,id', 
        ]);

        $template = AssetTemplate::find($request->input('template-id'));
        if ($template->name !== $request->input('name')) {
            if ($template->folder->assetTemplates()->where('name', $request->input('name'))->exists()) {
                return redirect()
                    ->back()
                    ->withErrors('Name already used inside this folder.');
            } 
        }
        $template->name = $request->input('name');
        $template->file_type = $request->input('type');
        $template->requirement = $request->input('requirement');
        $template->save();

        return redirect()
            ->back()
            ->with('success', 'success')
            ->with('message', 'Asset template updated.');
    }

    public function postDelete(Request $request)
    {
        $request->validate([
            'template-id' => 'required|integer|exists:asset_templates,id',
        ]);

        $template = AssetTemplate::find($request->input('template-id'));
        if (count($template->assets)) {
            return redirect()
                ->back()
                ->with('error', 'error')
                ->with('message', 'Asset template not empty.');
        }
        $template->delete();

        return redirect()
            ->back()
            ->with('success', 'success')
            ->with('message', 'Asset template deleted.');
    }
    
    public function getShow(AssetTemplate $template)
    {
        $assets = $template->assets()->orderBy('updated_at', 'desc')->paginate(15);
        return view('veeditor::asset-template.vapor-show', compact('template', 'assets'));
    }

    public function postSort(Request $request)
    {
        $request->validate([
            'sequence' => 'required|string|max:191',
        ]);

        $sequence = explode(',', $request->input('sequence'));
        if (count($sequence) <= 1) return response()->json(['error' => 'Not enough elements.'], 500);
        
        $success = AssetManager::sort($sequence);

        return $success ? response()->json(['success' => 'success'])
            : response()->json(['error' => 'error'], 500);
    }
}

src/resources/views/asset-template/show.blade.php
<x-veeditor::layout>
  <div x-data="{ showModal: false, showCreateModal: false, showDeleteModal: false, assetId: '' }">
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        VE Editor - {{ $template->folder->type_name }} ({{ $template->name }})
    </h2>
    </x-slot>

    <div class="flex justify-between">
      <a href="{{ route('ve-editor.folder.getShow', $template->folder_id) }}" class="cursor-pointer mx-2 my-2 w-auto bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Back</a>
      <button class="cursor-pointer mx-2 my-2 w-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" @click="showModal = true; showCreateModal = true;">Create Asset</button>
    </div>
    <table class="table-auto w-full">
      <thead>
        <tr>
          <th class="px-4 py-2 w-1/4">Created at</th>
          <th class="px-4 py-2 w-1/4">Dummy</th>
          <th class="px-4 py-2 w-auto">Action</th>
        </tr>
      </thead>
      <tbody>
        @forelse($assets as $asset)
        <tr>
          <td class="border px-4 py-2">{{ $asset->updated_at }}@if($loop->first) (Active) @endif</td>
          <td class="border px-4 py-2">@if($asset->dummy) Yes @else No @endif</td>
          <td class="border px-4 py-2">
            <a href="{{ $asset->url }}" target="_blank" class="mx-2 w-auto bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">View</a>
            <button data-content="{{ $asset->url }}" class="click-copy mx-2 w-auto bg-yellow-300 hover:bg-yellow-500 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Copy</button>
            <button @click="showModal = true; showDeleteModal = true; assetId = {{ $asset->id }}" class="mx-2 w-auto bg-red-600 hover:bg-red-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Delete</button>
          </td>
        </tr>
        @empty
        <tr>
          <td class="border px-4 py-2" colspan="4">No assets yet.</td>
        </tr>
        @endforelse
      </tbody>
    </table>
    <div class="py-3 px-3">
      {{ $assets->withQueryString()->links() }}
    </div>

    <div class="fixed w-screen h-screen left-0 flex justify-center top-0 items-center bg-gray-500 bg-opacity-25" x-show="showModal">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg" @click.away="showDeleteModal = false; showCreateModal = false; showUpdateModal = false; showModal = false">
          <form class="px-4 py-2 text-center container" x-show="showCreateModal" action="{{ route('ve-editor.asset.postCreate') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="flex-1 flex items-center my-2">
              <label for="create-file" class="w-28">File</label>
              <input type="file" id="create-file" name="file" class="mx-4 flex-1 shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <div class="flex-1 flex items-center my-2">
              <label for="create-dummy" class="w-28">Dummy</label>
              <input type="checkbox" id="create-dummy" name="dummy" class="mx-4 shadow border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <input type="hidden" name="template-id" value="{{ $template->id }}">
            <input type="submit" value="Create" class="cursor-pointer mx-2 my-2 w-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          </form>
          <form class="px-4 py-2 text-center container" x-show="showDeleteModal" action="{{ route('ve-editor.asset.postDelete') }}" method="POST">
            @csrf
            <p>Are you sure you want to delete this asset?</p>
            <label for="delete-id">
            <input type="text" class="mx-4 flex-1 shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" x-model="assetId" disabled>
            <input type="hidden" name="asset-id" x-model="assetId">
            <input type="submit" value="Delete" class="cursor-pointer mx-2 w-auto bg-red-600 hover:bg-red-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    let copy;
    window.addEventListener('load', function () {
      Array.from(document.querySelectorAll('.click-copy')).forEach(el => {
        el.addEventListener('click', function (e) {
          let text = this.dataset.content;
          copy(text);
          alert('Asset link copied to clipboard.');
        });
      })
    });

    copy = (str) => {
      let el = document.createElement('textarea');
      el.value = str;
      el.style.position = 'absolute';
      el.style.left = '-9999px';
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
    }
  </script>
</x-veeditor::layout>

src/resources/views/asset-template/vapor-show.blade.php
<x-veeditor::layout>
  @push('script')
  <script src="{{ asset('vendor/ve/js/asset-template-show.js') }}" defer></script>
  @endpush
  <input type="hidden" id="required-data" data-template-type="{{ $template->folder->folder_type }}">
  <div x-data="{ showModal: false, showCreateModal: false, showDeleteModal: false, assetId: '' }">
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        VE Editor - {{ $template->folder->type_name }} ({{ $template->name }})
    </h2>
    </x-slot>

    <div class="flex justify-between">
      <a href="{{ route('ve-editor.folder.getShow', $template->folder_id) }}" class="cursor-pointer mx-2 my-2 w-auto bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Back</a>
      <button class="cursor-pointer mx-2 my-2 w-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" @click="showModal = true; showCreateModal = true;">Create Asset</button>
    </div>
    <table class="table-auto w-full">
      <thead>
        <tr>
          <th class="px-4 py-2 w-1/4">Created at</th>
          <th class="px-4 py-2 w-1/4">Dummy</th>
          <th class="px-4 py-2 w-auto">Action</th>
        </tr>
      </thead>
      <tbody>
        @forelse($assets as $asset)
        <tr>
          <td class="border px-4 py-2">{{ $asset->updated_at }}@if($loop->first) (Active) @endif</td>
          <td class="border px-4 py-2">@if($asset->dummy) Yes @else No @endif</td>
          <td class="border px-4 py-2">
            <a href="{{ $asset->url }}" target="_blank" class="mx-2 w-auto bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">View</a>
            <button data-content="{{ $asset->url }}" class="click-copy mx-2 w-auto bg-yellow-300 hover:bg-yellow-500 text-black font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Copy</button>
            <button @click="showModal = true; showDeleteModal = true; assetId = {{ $asset->id }}" class="mx-2 w-auto bg-red-600 hover:bg-red-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Delete</button>
          </td>
        </tr>
        @empty
        <tr>
          <td class="border px-4 py-2" colspan="4">No assets yet.</td>
        </tr>
        @endforelse
      </tbody>
    </table>
    <div class="py-3 px-3">
      {{ $assets->withQueryString()->links() }}
    </div>

    <div class="fixed w-screen h-screen left-0 flex justify-center top-0 items-center bg-gray-500 bg-opacity-25" x-show="showModal">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg" @click.away="showDeleteModal = false; showCreateModal = false; showUpdateModal = false; showModal = false">
          <form id="create-form" class="px-4 py-2 text-center container" x-show="showCreateModal" action="{{ route('ve-editor.asset.postCreate') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="flex-1 flex items-center my-2">
              <label for="create-file" class="w-28">File</label>
              <input type="file" id="create-file" name="file" class="mx-4 flex-1 shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <div class="flex-1 flex items-center my-2">
              <label for="create-dummy" class="w-28">Dummy</label>
              <input type="checkbox" id="create-dummy" name="dummy" class="mx-4 shadow border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="1">
            </div>
            <input id="create-template-id" type="hidden" name="template-id" value="{{ $template->id }}">
            <input id="create-btn" type="button" value="Create" class="cursor-pointer mx-2 my-2 w-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          </form>
          <form class="px-4 py-2 text-center container" x-show="showDeleteModal" action="{{ route('ve-editor.asset.postDelete') }}" method="POST">
            @csrf
            <p>Are you sure you want to delete this asset?</p>
            <label for="delete-id">
            <input type="text" class="mx-4 flex-1 shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" x-model="assetId" disabled>
            <input type="hidden" name="asset-id" x-model="assetId">
            <input type="submit" value="Delete" class="cursor-pointer mx-2 w-auto bg-red-600 hover:bg-red-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    let copy;
    window.addEventListener('load', function () {
      Array.from(document.querySelectorAll('.click-copy')).forEach(el => {
        el.addEventListener('click', function (e) {
          let text = this.dataset.content;
          copy(text);
          alert('Asset link copied to clipboard.');
        });
      })
    });

    copy = (str) => {
      let el = document.createElement('textarea');
      el.value = str;
      el.style.position = 'absolute';
      el.style.left = '-9999px';
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
    }
  </script>
</x-veeditor::layout>